### ISSUE TITLE
16 bits tiff image (moiré)

### ISSUE THREAD

**Issue by jeanpat** [Image-Py/imagepy#11]
hello,
When loading via File>TIF>TIF Open a 16 bits tiff image, the image is displayed as a 8 bits image modulo 256 (I guess) yielding a nice moiré effect.

**Comment by yxdragon** [comment]
hi, I used to treat 8-bit and rgb image, so I did not treat 16-bit specifically. But it is not difficult, I will support float image and 16-bit image in the next push.  maybe in next week. Thanks for your advice, And do you want to join us?

**Comment by yxdragon** [comment]
@jeanpat Hi, Now it supports (uint8, uint16, int32, float32, float64), and you can use Image > Type > ... to transform from one to another.

and the newly added type are not tested fully, so please tell me if you find bug. Thanks.
