### ISSUE TITLE
No module named 'imagepy.core'

### ISSUE THREAD

**Issue by alan0526** [Image-Py/imagepy#145]
Error occured after I install the open plugin in the Plugins manager

File                          	Name                	Error
plugins\opencv-plgs\menus\Opencv\Filters	laplace_plg.py      	No module named 'imagepy.core'
plugins\opencv-plgs\menus\Opencv\Filters	canny_plg.py        	No module named 'imagepy.core'
plugins\opencv-plgs\menus\Opencv\Segmentation	awatershed_plg.py   	No module named 'imagepy.core'
plugins\opencv-plgs\menus\Opencv\Segmentation	means_plg.py        	No module named 'imagepy.core'
plugins\opencv-plgs\menus\Opencv\Segmentation	shift_plg.py        	No module named 'imagepy.core'
plugins\opencv-plgs\menus\Opencv\Threshold	athreshold_plg.py   	cannot import name 'IPy' from 'imagepy' (F:\work\github\imagepy\imagepy\__init__.py)
plugins\opencv-plgs\menus\Opencv\Video IO	io_plgs.py          	No module named 'imagepy.core'

**Comment by alan0526** [comment]
It should be "from sciapp.action import Filter"

**Comment by alan0526** [comment]
It is the bug of opencv plugin

**Comment by dada1437903138** [comment]
> Error occured after I install the open plugin in the Plugins manager
> 
> File Name Error
> plugins\opencv-plgs\menus\Opencv\Filters laplace_plg.py No module named 'imagepy.core'
> plugins\opencv-plgs\menus\Opencv\Filters canny_plg.py No module named 'imagepy.core'
> plugins\opencv-plgs\menus\Opencv\Segmentation awatershed_plg.py No module named 'imagepy.core'
> plugins\opencv-plgs\menus\Opencv\Segmentation means_plg.py No module named 'imagepy.core'
> plugins\opencv-plgs\menus\Opencv\Segmentation shift_plg.py No module named 'imagepy.core'
> plugins\opencv-plgs\menus\Opencv\Threshold athreshold_plg.py cannot import name 'IPy' from 'imagepy' (F:\work\github\imagepy\imagepy__init__.py)
> plugins\opencv-plgs\menus\Opencv\Video IO io_plgs.py No module named 'imagepy.core'

Did you solve this problem?

**Comment by yxdragon** [comment]
now cv plugins is ok

**Comment by liupeng0606** [comment]
Did you solve this problem?  No module named 'imagepy.core'
