### ISSUE TITLE
Dicom image import issues

### ISSUE THREAD

**Issue by xycyx** [Image-Py/imagepy#15]
**1. Incorrect display for 16 uint dicom file**
When I load a 4D uint16 grey scale dicom file to the software, it displayed the image with some issues like below:
![capture1](https://user-images.githubusercontent.com/16574534/37673405-5b281d44-2c2d-11e8-8e16-60137f770982.PNG)
After converting to 8-bit, it recognizes it as 8-bit RGB.
![capture2](https://user-images.githubusercontent.com/16574534/37673416-614197a0-2c2d-11e8-865d-42a8e31797be.PNG)

**2. Cannot display 3D image
Only displayed the first slice of 3D image.
Is it possible to load the 3D image from dicom or video file instead of using the a sequence of 2D images?

Thanks.

A 4-D dicom example (x, y, channel, z):
[test_dicom.zip](https://github.com/Image-Py/imagepy/files/1830529/test_dicom.zip)

**Comment by yxdragon** [comment]
@xycyx thanks, I saw, ImagePy now did not support 4D image, I will have a look how ImageJ do! I think it is not real 4D, It is just a sequence of 3D, I will think how to display "4D".
About reading 3D image, https://github.com/Image-Py/itk-plgs, some ITK plugins, and you can add new format reader and writer esaily.
About reading video, I would write some demo and upload here: https://github.com/Image-Py/opencv-plgs.
(ImagePy is just a pure python framework, based on numpy, scipy, scikit-image, And I would to build many plugins with opencv, tf, itk... finally build a image processing ecosystem, and user can write and upload their plugins to ImagePy)
