### ISSUE TITLE
Can’t install python plugin

### ISSUE THREAD

**Issue by aseedb** [Image-Py/imagepy#19]
I have tried to install a python plugin by copying the code in the Gaussian filter example and saving in to a .py file in the menu directory or a sub directory but it won’t show in imagepy after I restart it. I have also
Tried editing the __init__.py files in the directories but this didn’t help.

**Comment by aseedb** [comment]
I found the problem. I had to add 
`plgs = [Class_name]` 
at the end of my plugin file

**Comment by yxdragon** [comment]
@aseedb sorry to not response in time. Yes, you can subclass Filter/Simple/Free and overwrite the run function. if you write only one plugin in a file, you can Name the class as Plugin. Else you can write many plugin in one file, and add a plgs = [Plugin1, Plugin2, '-', Plugin3...] the '-' would be parsed as a spliter.

and you need not copy the file under menus folder, you can build a github project like this, [and](https://github.com/Image-Py/demoplugin) use Plugins > Install > Install Plugins, input the git path, then imagepy would install it automotive.

Sorry, the document is out-date, and ImagePy is going through a bit upgrade!  It will coming soon!
