### ISSUE TITLE
ValueError: insecure string pickle

### ISSUE THREAD

**Issue by XianchaoZhang** [Image-Py/imagepy#2]
首先非常感谢你分享的这个优秀工具，目前我遇到了一些问题，还没有在本地运行起来

我使用的发行版是Anaconda2 和wxPython，运行命令python main.py遇到了如下错误：

```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
    from ui.imagepy import ImagePy
  File "C:\apps\imagepy\ui\imagepy.py", line 8, in <module>
    import pluginloader, toolsloader, IPy
  File "C:\apps\imagepy\ui\pluginloader.py", line 3, in <module>
    from core.loader import loader
  File "C:\apps\imagepy\core\loader\loader.py", line 7, in <module>
    import IPy
  File "C:\apps\imagepy\IPy.py", line 8, in <module>
    from ui.panelconfig import ParaDialog
  File "C:\apps\imagepy\ui\panelconfig.py", line 3, in <module>
    from core.managers import WindowsManager, TableLogManager
  File "C:\apps\imagepy\core\managers.py", line 12, in <module>
    from manager.configmanager import *
  File "C:\apps\imagepy\core\manager\configmanager.py", line 34, in <module>
    ConfigManager.read()
  File "C:\apps\imagepy\core\manager\configmanager.py", line 15, in read
    cls.cfg = pickle.load(pkl_file)
  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 1384, in load
    return Unpickler(file).load()
  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 864, in load
    dispatch[key](self)
  File "C:\ProgramData\Anaconda2\lib\pickle.py", line 972, in load_string
    raise ValueError, "insecure string pickle"
ValueError: insecure string pickle
```
下面是我的环境变量：
`['C:\\apps\\imagepy', 'C:\\ProgramData\\Anaconda2\\python27.zip', 'C:\\ProgramData\\Anaconda2\\DLLs', 'C:\\ProgramData\\Anaconda2\\lib', 'C:\\ProgramData\\Anaconda2\\lib\\plat-win', 'C:\\ProgramData\\Anaconda2\\lib\\lib-tk', 'C:\\ProgramData\\Anaconda2', 'C:\\ProgramData\\Anaconda2\\lib\\site-packages', 'C:\\ProgramData\\Anaconda2\\lib\\site-packages\\Sphinx-1.5.1-py2.7.egg', 'C:\\ProgramData\\Anaconda2\\lib\\site-packages\\win32', 'C:\\ProgramData\\Anaconda2\\lib\\site-packages\\win32\\lib', 'C:\\ProgramData\\Anaconda2\\lib\\site-packages\\Pythonwin', 'C:\\ProgramData\\Anaconda2\\lib\\site-packages\\setuptools-27.2.0-py2.7.egg', 'C:\\ProgramData\\Anaconda2\\lib\\site-packages\\wx-3.0-msw']`

**Comment by yxdragon** [comment]
@XianchaoZhang 删掉preference.cfg试试呢，这是一个配置文件，用于保留一些信息，比如打开图像时默认回到上次的目录，这个文件是我在ubuntu上生成的，不知道是不是这里的问题。另外，我用了最新版的wxpython-phoenix，可能需要更新到phoenix。

如果还有问题，可以加我的QQ：498264240，或者搜索ImagePy这个群。
感谢你的关注，另外，最近在添加多线程支持，会更新的比较频繁，当然一部分功能可能不稳定，希望理解，个人项目，只能一步一步来，有兴趣可以加入。

**Comment by XianchaoZhang** [comment]
安装了wxPython-Phoenix，终于运行起来了。（PS. 之前用的是wxPython）

```
(C:\ProgramData\Anaconda2) C:\apps\python64+wxphoenix>pip install "wxPython_Phoenix-3.0.3.dev2832+e3fbb9f-cp27-cp27m-win_amd64.whl"
Processing c:\apps\python64+wxphoenix\wxpython_phoenix-3.0.3.dev2832+e3fbb9f-cp27-cp27m-win_amd64.whl
Requirement already satisfied: six in c:\programdata\anaconda2\lib\site-packages (from wxPython-Phoenix==3.0.3.dev2832+e3fbb9f)
Installing collected packages: wxPython-Phoenix
Successfully installed wxPython-Phoenix-3.0.3.dev2832+e3fbb9f
```

```
C:\apps\imagepy>python main.py
['ImagePy']
```

另外有个建议，可以把依赖的包列出来，这样在使用其他发行版做开发扩展时更容易搭建环境。

**Comment by frankylo** [comment]
请问 我用eclipse 执行main()  提示    import pluginloader, toolsloader, IPy
ImportError: No module named 'toolsloader' 该怎么解决呢。

**Comment by ausk** [comment]
Fixed in the new version!
