### ISSUE TITLE
打包imagepy成exe文件

### ISSUE THREAD

**Issue by wb-finalking** [Image-Py/imagepy#30]
我在使用pyinstaller打包imagepy后，点击exe文件闪退，分析原因应该是没有将需要的文件都打包进去，由于imagepy是以插件的形式管理的，我想是不是因为启动时管理器去扫描插件然后再加载插件导致打包不进去

**Comment by yxdragon** [comment]
有可能的呢，我最近也有打包需求，要不你加一下群，我们讨论一下怎么解决？QQ 群：596310256
may be, please join our qq group then talk about how to solve it, 596310256
