### ISSUE TITLE
web out of service

### ISSUE THREAD

**Issue by Borda** [Image-Py/imagepy#43]
Hello, 
I was wondering about the home page - http://imagepy.org but it seems that there is an issue to access this page:
```
This site can’t be reached imagepy.org’s server IP address could not be found.
Try:
    Checking the connection
    Checking the proxy, firewall, and DNS configuration
ERR_NAME_NOT_RESOLVED
```

**Comment by yxdragon** [comment]
Hi, [](http://www.imagepy.org/) is OK, will have a look, may be I did not parse the main domain.
(but the document is in Chinese, and a little out date, I did not have so much time on working both develop and document, [Here](https://github.com/Image-Py/demoplugin) is a demo plugin repo, may be it is also a little out date, And I will update the demo repo and it's readme document soon, If you want to integrate your algrithsm, I am very glad to give any help, be free to contact with me!)

**Comment by Borda** [comment]
I would be more then happy if the documentation will be in English, otherwise, it is very hard to be used outside China...

**Comment by yxdragon** [comment]
Hi, last week, we translate the newest development document, and wrote a demo plugin repo [here](https://github.com/Image-Py/demoplugin).
