### ISSUE TITLE
PyStackReg missing for Windows on conda

### ISSUE THREAD

**Issue by LauLauThom** [Image-Py/imagepy#50]
Since (fb0f9a14ac3f88c159a486cea13292aab6f7e777), using the environnement.yml with Pystackreg as dependency to install imagepy with anaconda fails on windows because the [package ](https://anaconda.org/search?q=pystackreg) is only available for Linux on anaconda.
```
PackageNotFoundError: Packages missing in current channels:

  - pystackreg
```

**Comment by BioinfoTongLI** [comment]
For instance, you can ignore it by simply `pip install pystackreg`, and it should work.
But yes, you are right. For the late comers, It seems a win-based conda package would simplify everything.
For my knowledge, this pystackreg project is not on Github, but on [bitbucket](https://bitbucket.org/glichtner/pystackreg/issues?status=new&status=open). 
Maybe we should ask the pystackreg's maintainer to add a win-based release?

**Comment by LauLauThom** [comment]
I tested the pip installation on windows and it works, hence the [pull request](https://github.com/Image-Py/imagepy/pull/51)

**Comment by yxdragon** [comment]
It is difficult to install pystackreg on python3.7, and it is a gpl project, So remove it from master and publish as a plugin?

**Comment by LauLauThom** [comment]
That could be an option too 👍
