### ISSUE TITLE
Add pip requirements.txt

### ISSUE THREAD

**Issue by Metallicow** [Image-Py/imagepy#6]
Add pip requirements.txt

**Comment by yxdragon** [comment]
@Metallicow : thanks, I will add it.

**Comment by yxdragon** [comment]
@Metallicow requirements.txt added and I moved the project to a Image-Py orgnization, Please have a try, and if you are intrested in.

**Comment by Metallicow** [comment]
Sorry, but I don't see a commit for it. Where did you place it?

**Comment by yxdragon** [comment]
sorry, I saw "Latest commit 6 days ago"... Let me see why I commit failed...   by the way, do you known if i can write requirements like "xxx >= 1.1"?

**Comment by yxdragon** [comment]
Now it's ok

numpy==1.12.0+mkl
Pillow==4.0.0
scipy==0.19.0
Shapely==1.5.17
wxPython-Phoenix==3.0.3.dev2832+e3fbb9f

need i wrote "dev2832+e3fbb9f"?
and if I can use ">="?

**Comment by Metallicow** [comment]
wxPython is on pypi now.
wxPython is just fine.

**Comment by yxdragon** [comment]
on windows pip install wxpython works. but on linux and mac not.

**Comment by Metallicow** [comment]
might be an issue with the pip version.

**Comment by bastula** [comment]
pip install wxpython does work on the Mac properly now.

**Comment by yxdragon** [comment]
@bastula Yes, only on the windows works. 

Are you the author of pydicom? pleasure to meet you! I had wrote a plugin using pydicom in my ImagePy, can we support compressed dicom? I just want to read and write, So It is too heavy to use SimpleITK.

**Comment by bastula** [comment]
@yxdragon I am not the author of @pydicom, but actually @dicompyler if you have used it.

There has been recent work performed on pydicom master that should allow compressed images to be decoded via various other modules i.e. gdcm, pillow, etc.

See: https://github.com/pydicom/pydicom/tree/0e52af241f2d5405f4ffaf47aa992c58f9cd4421/pydicom/pixel_data_handlers for the various data handlers and what formats they support. I wonder if a feature enhancement to pydicom is to list what transfer syntaxes are supported.

**Comment by steeveen** [comment]
emmmm，例子里给出了3D效果，但是这个功能怎么使用呢。
我现在用file->import导入了图像序列，使用ToolKit3D的时候控制台崩溃了……
是我的使用方法不对么，还是代码里有问题，还是我的数据集太大了？（512*512*591）
还是什么其他问题呢，很不明白。

**Comment by yxdragon** [comment]
@steeveen 最大数据我跑过1024^3，应该是操作问题，更多三维的例子可以看我都这个项目 [Myvi](https://github.com/yxdragon/myvi)，具体操作和使用方法交流，欢迎加群QQ : 596310256。

**Comment by jakirkham** [comment]
This can be closed, right?

**Comment by HamburgerZ** [comment]
请问在ImagePy调色阶或者阈值的时候，那些灰度直方图是如何绘制的？是用matplotlib吗？

**Comment by yxdragon** [comment]
@jakirkham yes! can be closed.

**Comment by yxdragon** [comment]
@HamburgerZ 可以用matplotlib，我这里直接用的wx的dc绘制的，这样效率更高，并且基础框架并不依赖matplotlib。
