### ISSUE TITLE
wxpython-installer in requirements

### ISSUE THREAD

**Issue by Czaki** [Image-Py/imagepy#60]
I try to install imagepy with pip and fail because cannot install wxpython-installer. I also do not found it on pypi. Could you update requirements in setup.py file?

**Comment by BioinfoTongLI** [comment]
Hi, if you don't mind using Conda, here is an easier way to install imagepy
```
git clone git://github.com/Image-Py/imagepy
cd imagepy
conda env create
conda activate imagepy
python -m imagepy
```
More details here https://forum.image.sc/t/how-to-install-and-run-imagepy/21923

**Comment by Czaki** [comment]
In repo there is 0.20 version. on pypi there is 0.21?

**Comment by BioinfoTongLI** [comment]
What do you mean ? If you want to run the latest version, try the method described above.
It's running from your downloaded source code.

**Comment by Czaki** [comment]
I run it, even I create pull request with small change. 
My question is why on pypi there is reported never version. 
And whole issue is about this that imagepy is not pip instalable because there is no wxpython-installer on pypi
https://pypi.org/project/wxpython-installer/

**Comment by BioinfoTongLI** [comment]
Yeah, you are right. `pip` version is broken lately due to recent changes in `skimage`.
It will be fixed when @yxdragon is available.

**Comment by yxdragon** [comment]
pip install wxpython did not work on linux, So wxpython-installer is a helper package to install wxpython. But now, wxpython seems wrok on linux, and I did not update the installer package and imagepy for a long while. So, you failed. @Czaki 

I will update imagepy's pip package soon, and tell you. thanks for your pr.

**Comment by yxdragon** [comment]
I had tested pip install all package works now, (numpy, scipy, even numba, llvlime), but only shapely not work on windows. Any advice?

**Comment by Czaki** [comment]
@yxdragon. I do not understand your response. I have had installed imagepy. I do not need anaconda for this. My remark is that imagepy is no pypi but is not pip installable. 

Also confirm that wxpython start to be possible to install on Linux with `pip install wxpython`, if you have python shared object library (I work on pyenv python versions, so need to recompile python).

I do not know what to do with sharpely. on pypi there is no whl for windows ( maybe write custom installer https://www.lfd.uci.edu/~gohlke/pythonlibs/#shapely). I work on Linux and Macos

**Comment by yxdragon** [comment]
@Czaki I had updated imagepy on pypi. (remove wxpython-installer)!

**Comment by Czaki** [comment]
it works. But on linux needs to install pathlib2.
