### ISSUE TITLE
there is an error when I run imagepy

### ISSUE THREAD

**Issue by NeroAsmarr** [Image-Py/imagepy#75]
macos 10.15.1
Python 3.7.5

after run `pip install imagepy` install imagepy
then run `imagepy' or `python -m imagepy` I get an error:
```
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.
```

**Comment by yxdragon** [comment]
@NeroAsmarr do you run imagepy on e visual environment？please try pythonw -m imagepy!

**Comment by NeroAsmarr** [comment]
thanks!!! done.

**Comment by NeroAsmarr** [comment]
> @NeroAsmarr do you run imagepy on e visual environment？please try pythonw -m imagepy!

thanks!!! done.
