### ISSUE TITLE
Support maths in markdown

### ISSUE THREAD

**Issue by CsatiZoltan** [Image-Py/imagepy#78]
ImagePy uses *Python-Markdown*, which can be extended for maths support using several [extensions](https://github.com/Python-Markdown/markdown/wiki/Third-Party-Extensions#math--latex). I myself tried [this one](https://github.com/mitya57/python-markdown-math). To enable, you need to append the [exts](https://github.com/Image-Py/imagepy/blob/e5831570d5c00600e11e687f9cd451d9485567f3/imagepy/ui/mkdownwindow.py#L7) list with `'mdx_math'` in the `imagepy/ui/mkdownwindow.py` file. For instance, `markdown("$$x^2$$", extensions=['mdx_math'])` results in the HTML code `'<p>\n<script type="math/tex; mode=display">x^2</script>\n</p>'`. This trick alone is not enough in ImagePy, the documentation writes that some [additional steps](https://github.com/mitya57/python-markdown-math#usage) are needed. Could you implement this? It would be very useful for displaying formulas in help texts.

**Comment by yxdragon** [comment]
hi, I try the code, and got the '<p>\n<script type="math/tex; mode=display">x^2</script>\n</p>'

but I am not aware of web, can you show me how to config the js? I got a blank page with the code below:
```
<html lang="zh-cn">
<head>
<meta content="text/html; charset=utf-8" http-equiv="content-type" />
</head>

<body>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js"></script>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      config: ["MMLorHTML.js"],
      jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
      extensions: ["MathMenu.js", "MathZoom.js"]
    });
</script>

<p>
    <script type="math/tex; mode=display">x^2</script>
</p>

</body>
</html>
```

**Comment by CsatiZoltan** [comment]
@yxdragon It's a blank page for me too. There is a [related issue](https://github.com/mitya57/python-markdown-math/issues/24). I wrote there and I am waiting for the response...

**Comment by yxdragon** [comment]
@CsatiZoltan It is OK, swap the order of two script
```
<html lang="zh-cn">
<head>
<meta content="text/html; charset=utf-8" http-equiv="content-type" />
</head>

<body>

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      config: ["MMLorHTML.js"],
      jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
      extensions: ["MathMenu.js", "MathZoom.js"]
    });
</script>

<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js"></script>

</body>

<p>
    <script type="math/tex; mode=display">x^2</script>
</p>

</html>
```

I will try to integrate in imagepy

**Comment by CsatiZoltan** [comment]
Based on the [author's comment](https://github.com/mitya57/python-markdown-math/issues/24#issuecomment-579717033), here is the modified MWE:

```html
<html lang="en">

<head>

<meta content="text/html; charset=utf-8" http-equiv="content-type" />

<script type="text/x-mathjax-config">
    MathJax.Hub.Config({
      config: ["MMLorHTML.js"],
      jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
      extensions: ["MathMenu.js", "MathZoom.js"]
    });
</script>

<script type="text/javascript" 

src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js"></script>

</head>

<p>
    <script type="math/tex; mode=display">x_2^2</script>
</p>

</html>
```

**Comment by yxdragon** [comment]
@CsatiZoltan Now it is OK, have a try.

**Comment by CsatiZoltan** [comment]
I have two ideas in mind: if the user is offline,
1. do not render the math
2. render using the offline version of MathJax ([see here](https://docs.mathjax.org/en/v2.7-latest/configuration.html); the latest version is [33 MB](https://github.com/mathjax/MathJax/archive/2.7.5.zip). It could be bundled with *ImagePy* if its license is compatible with [Apache 2.0](https://github.com/mathjax/MathJax/blob/master/LICENSE).

**Comment by yxdragon** [comment]
now if offline only do not render math, others is ok.

about using offline mathjax, it could be a plugin like IBook, because it is large, and not necessary.

**Comment by CsatiZoltan** [comment]
I agree.
