### ISSUE TITLE
Automatic conversion from int to float causes segfault

### ISSUE THREAD

**Issue by CsatiZoltan** [Image-Py/imagepy#85]
When I tick the `preview` checkbox, the `para-changed` method is invoked. This implicitly converts an int to a float. In the screenshot below you can see that the value for the `'window_size'` key in the `para` dictionary is 5 as an int. However, after executing line 101, the result is a float, as shown in the right window.
![int-float](https://user-images.githubusercontent.com/12742890/74740195-b37bf100-525a-11ea-8820-c251a7082b09.png)
The error arises in this file: https://github.com/Image-Py/imagepy/blob/c0804fa690d7f0a52acc948b9f17067f7b2c0397/imagepy/ui/panelconfig.py#L101

Code to reproduce:
```python
from imagepy.core.engine import Filter
from scipy.ndimage import median_filter

class FilterImage(Filter):
    title = 'Filter image'
    note = ['all', 'auto_msk', 'auto_snap', 'preview']
    para = {'window_size': 5}
    view = [(int, 'window_size', (0, 30), 1, 'window size', 'pixel')]

    def run(self, ips, snap, img, para=None):
        median_filter(snap, para['window_size'], output=img)

plgs = [FilterImage, '-']
```
This is almost the same as your [`Gaussian` class](https://github.com/Image-Py/demoplugin/blob/master/menus/Demos/Filter%20Demo/filtersdemo_plgs.py), with the exception that I defined an integer. When the `median_filter` function of scipy.ndimage receives a float, it terminates with a segmentation fault.

**Comment by yxdragon** [comment]
view = [(int, 'window_size', (0, 30), 1, 'window size', 'pixel')]
please use:
view = [(int, 'window_size', (0, 30), 0, 'window size', 'pixel')]

for loat, it is the accuracy. I want to keep a same format with the float, so put 0 there.

**Comment by CsatiZoltan** [comment]
My bad, now it works. Thanks.
