### ISSUE TITLE
More lax array type check

### ISSUE THREAD

**Issue by CsatiZoltan** [Image-Py/imagepy#88]
The *Mark Boundaries* command requires an integer type https://github.com/Image-Py/imagepy/blob/9710a277ad5711ca91c19c9324cb1bc18f4e2ff6/imagepy/menus/Analysis/label_plg.py#L34 This is however not required because the *find_boundaries* function of scikit-image [accepts bool](https://github.com/scikit-image/scikit-image/blob/d323ed1f25c5f8cbfcca2a55b4564d6fdff7a4d5/skimage/segmentation/boundaries.py#L159) type too. Boolean types could be implemented in the `note` list as `'bool'`.

---

In some cases, one could accept an RGB image and implicitly convert it to e.g. `uint8` when necessary. The *Filter* plugin already supports auto-conversion, as described in the [documentation](https://github.com/Image-Py/demoplugin/blob/master/doc/filter.md), in the form of `'2int'` and `'2float'`. What about implementing `'rgb2uint32`, `rgb2uint64`, etc.?

**Comment by yxdragon** [comment]
for bool is a "detyped uint8", and it cost the same memory as uint8. we use imread, imsave to treat bool, it also come into uint8. So there is no need to treat bool as a specific type.

and the 2int, 2float is for keeping the accuracy in filters, that means if the dtype is lower than float: xxx 2 float, float count, result 2xxx. but we can not define int2rgb. So I we need treat it, using Image > Type > to transfrom.

**Comment by CsatiZoltan** [comment]
> not generate new window

Most plugins modify the current image but some create a new image (e.g. Analysis -> Mark Boundaries). How do you decide whether to create a new image or not?

**Comment by yxdragon** [comment]
filter means modify inplace, and the Filter base class will loop the images sequence by default.

but some operation return different dtype, So we use simple, and we must treat sequence by a for loop.  then show a new one.

We can not show new image in a filter, else it would pop many windws when processing sequence.
