### ISSUE TITLE
How to get stacked Imgs?

### ISSUE THREAD

**Issue by steeveen** [Image-Py/imagepy#9]
emmm,大佬，我现在想用这个库做3D建模，我想Toolkit3D应该就是这个功能的相关模块吧，我是通过序列导入来吧待建模的图像导入到程序中的，但是每次我调用ToolKit3D的时候他总是提示我需要堆叠的3d图像，emm，我看了一下Image菜单下的内容，不是很懂。所以我想知道怎么样才能得到可供3D重建的stacked3d的图像呢
致敬

**Comment by yxdragon** [comment]
@steeveen 是这样的，ImagePy里面三维分为两种，一种是离散序列，一种是连续块。各有好处。离散的可以动态删除和添加，而连续的可以用于三维分析。可以通过 Image > type > trans to stack   Image > type > trans to list 进行相互转换。

**Comment by yxdragon** [comment]
@steeveen 创建就是考虑到这种问题，我用nabble搭建了一个论坛，可以在里面贴图，发帖，提问，比较方便。 中文地址：http://luntan.imagepy.org/   英文地址：http://forum.imagepy.org/

**Comment by steeveen** [comment]
嗯，谢谢大佬，我已经解决我的问题了，现在在更深一步的研究中，
