### ISSUE TITLE
What causes Simple change the color of an image?

### ISSUE THREAD

**Issue by CsatiZoltan** [Image-Py/imagepy#91]
I have an input RGB image:
![homogeneous_1_cropped](https://user-images.githubusercontent.com/12742890/75145205-cbd78a00-56f8-11ea-9d3c-cde65da21ef3.png)
If I apply *Process -> Filter -> Median* on it, I obtain the following filtered image:
![filtered_1](https://user-images.githubusercontent.com/12742890/75145348-0fca8f00-56f9-11ea-9766-0c2673789ff8.png)
The median filter in *ImagePy* inherits from class `Filter`. However, if I want to replicate the same process using the `Simple` class, I get a different color:
![filtered_2](https://user-images.githubusercontent.com/12742890/75145676-b2830d80-56f9-11ea-8726-f1d568c648e4.png)
Why is it so? How can I keep the original color? My code is:
```python
class FilterImage(Simple):
    """Median filtering of the current image."""
    title = 'Filter image'
    note = ['all', 'auto_msk', 'auto_snap', 'preview']
    para = {'size': 5}
    view = [(int, 'size', (1, 30), 0, 'window size', 'pixel')]

    def run(self, ips, imgs, para=None):
        out = median_filter(ips.img, para['size'])
        IPy.show_img([out], ips.title + '-filtered')
```
Additional information:
- motivation: the only reason I subclass `Simple` and don't use the already available `Median` class is because I want to show the filtered image on a new tab, not overwriting the original one. Yes, I know, I could first duplicate the original image and perform the filtering on it, but still, I am curious why this color issue happens.
- *ImagePy* still shows the third image as RGB (first I thought that the change in color is due to the an implicit conversion to an *int* type)
- I realized that even if I change the above code to
   ```python
   def run(self, ips, imgs, para=None):
           imgs[0] = median_filter(ips.img, para['size'])
   ```
   the same color change happens. It means that it is not `IPy.show_img` that causes the issue.

**Comment by yxdragon** [comment]
because median_filter treat the rgb image as a 3d image, So do filter in a cube.

you can loop the z channels yourself, or there is a skimage function can help you to go though the channels, (but I forgot the name).

you can see filter's base class, the 'not_channel' note. That's why the filter can fit multi-channels image.

**Comment by yxdragon** [comment]
by the way: how to upload image in issue?

**Comment by CsatiZoltan** [comment]
> how to upload image in issue?

Simply drag&drop the image.

**Comment by yxdragon** [comment]
just have a try
![coins](https://user-images.githubusercontent.com/24822467/75152475-10d4de00-5744-11ea-9200-f15c3d0566bc.PNG)

**Comment by yxdragon** [comment]
[平差结果.xlsx](https://github.com/Image-Py/imagepy/files/4244535/default.xlsx)

**Comment by CsatiZoltan** [comment]
@yxdragon Just a tip: you can test whether uploading works without posting a message. After the drag&drop, click on the `Preview` tab.
